import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import img_to_array
from PIL import Image

# ---------------- PAGE SETTINGS ---------------- #

st.set_page_config(
    page_title="Brain Tumor Detection",
    page_icon="🧠",
    layout="centered"
)

# ---------------- CUSTOM CSS ---------------- #

st.markdown("""
<style>

.stApp{
    background-color:#0E1117;
}

h1{
    color:#4CAF50;
    text-align:center;
}

div[data-testid="stFileUploader"]{
    border:2px dashed #4CAF50;
    border-radius:10px;
    padding:15px;
}

.footer{
    text-align:center;
    color:gray;
    font-size:14px;
}

</style>
""", unsafe_allow_html=True)

# ---------------- LOAD MODEL ---------------- #

model = load_model("brain_tumor_model.keras")

classes = [
    "glioma",
    "meningioma",
    "notumor",
    "pituitary"
]

display_names = {
    "glioma": "Glioma",
    "meningioma": "Meningioma",
    "notumor": "No Tumor",
    "pituitary": "Pituitary"
}

# ---------------- SIDEBAR ---------------- #

st.sidebar.title("🧠 Tumor Types")

st.sidebar.markdown("""
🟢 **Glioma**

🟠 **Meningioma**

🔵 **No Tumor**

🟣 **Pituitary**
""")

# ---------------- TITLE ---------------- #

st.title("🧠 Brain Tumor Detection")

st.write(
"""
Upload an MRI brain image to predict the tumor category using a trained Deep Learning model.
"""
)

# ---------------- FILE UPLOAD ---------------- #

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg","jpeg","png"]
)

# ---------------- PREDICTION ---------------- #

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(
        image,
        caption="Uploaded MRI Image",
        use_container_width=True
    )

    img = image.resize((256,256))

    img_array = img_to_array(img)
    img_array = img_array/255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)

    predicted = classes[np.argmax(prediction)]
    confidence = np.max(prediction)*100

    st.success(f"Prediction: {display_names[predicted]}")
    st.info(f"Confidence: {confidence:.2f}%")

    # ---------------- DOWNLOAD REPORT ---------------- #

    report = f"""
=============================
BRAIN TUMOR DETECTION REPORT
=============================

Prediction : {display_names[predicted]}

Confidence : {confidence:.2f} %

--------------------------------

This report is automatically generated by
the Brain Tumor Detection System.

Disclaimer:
This application is intended only for
educational and research purposes.
It is NOT a substitute for professional
medical diagnosis.
"""

    st.download_button(
        label="📄 Download Prediction Report",
        data=report,
        file_name="Brain_Tumor_Report.txt",
        mime="text/plain"
    )

    # ---------------- TUMOR INFORMATION ---------------- #

    st.subheader("About the Predicted Class")

    if predicted == "glioma":

        st.write("""
**Glioma** is a tumor that develops from glial cells in the brain.

**Common Symptoms**
- Persistent headache
- Seizures
- Memory problems
- Difficulty speaking
- Blurred vision

**Treatment**
- Surgery
- Radiation Therapy
- Chemotherapy
""")

    elif predicted == "meningioma":

        st.write("""
**Meningioma** develops in the membranes surrounding the brain.

**Common Symptoms**
- Headache
- Vision changes
- Hearing problems
- Weakness
- Memory loss

**Treatment**
- Surgery
- Radiation Therapy
- Observation
""")

    elif predicted == "pituitary":

        st.write("""
**Pituitary Tumor** develops in the pituitary gland.

**Common Symptoms**
- Hormonal imbalance
- Vision problems
- Headache
- Fatigue
- Weight changes

**Treatment**
- Medication
- Surgery
- Radiation Therapy
""")

    else:

        st.write("""
**No Tumor** was detected by the model.

If symptoms persist, consult a qualified healthcare professional for further evaluation.
""")

# ---------------- DISCLAIMER ---------------- #

st.markdown("---")

st.warning("""
**Disclaimer**

This application is developed **only for educational and research purposes**.

The prediction generated by this model should **NOT** be considered a medical diagnosis or used to make treatment decisions.

Always consult a qualified radiologist or healthcare professional for an accurate diagnosis.
""")

# ---------------- FOOTER ---------------- #

st.markdown(
"""
<div class="footer">

🧠 Brain Tumor Detection using Deep Learning

</div>
""",
unsafe_allow_html=True
)